# Generated by Django 3.0.5 on 2020-05-22 20:43

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WorkOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('activity', models.CharField(max_length=100)),
                ('costCenter', models.CharField(max_length=50)),
                ('entryUser', models.CharField(max_length=50)),
                ('entryDt', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='WOOtherContract',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ocDt', models.DateField()),
                ('ocType', models.CharField(max_length=10)),
                ('ocDesc', models.CharField(max_length=100)),
                ('ocCost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('woid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mms.WorkOrder')),
            ],
        ),
        migrations.CreateModel(
            name='WOMaterial',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('mtDt', models.DateField()),
                ('mtDesc', models.CharField(max_length=100)),
                ('mtQty', models.DecimalField(decimal_places=1, max_digits=10)),
                ('mtRate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('woid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mms.WorkOrder')),
            ],
        ),
        migrations.CreateModel(
            name='WOLabor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('lbDt', models.DateField()),
                ('employee', models.CharField(max_length=100)),
                ('hours', models.DecimalField(decimal_places=1, max_digits=4)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('woid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mms.WorkOrder')),
            ],
        ),
        migrations.CreateModel(
            name='WOEquip',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('equipDt', models.DateField()),
                ('equipDesc', models.IntegerField()),
                ('equipId', models.IntegerField()),
                ('meterUsage', models.DecimalField(decimal_places=1, max_digits=10)),
                ('meterType', models.CharField(max_length=10)),
                ('equipRate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('woid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mms.WorkOrder')),
            ],
        ),
        migrations.CreateModel(
            name='WOAsset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('assetDt', models.DateField()),
                ('assetType', models.CharField(max_length=20)),
                ('assetIdentifier', models.CharField(max_length=25)),
                ('assetLat', models.DecimalField(decimal_places=15, max_digits=17)),
                ('assetLong', models.DecimalField(decimal_places=15, max_digits=17)),
                ('assetLogStart', models.DecimalField(decimal_places=2, max_digits=6)),
                ('assetLogEnd', models.DecimalField(decimal_places=2, max_digits=6)),
                ('assetAccomplishment', models.DecimalField(decimal_places=1, max_digits=5)),
                ('woid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mms.WorkOrder')),
            ],
        ),
    ]
