# Generated by Django 3.0.6 on 2020-05-27 01:50

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('projectName', models.CharField(max_length=100)),
                ('county', models.CharField(blank=True, max_length=4)),
                ('district', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='WorkOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tcoreCoreFunction', models.CharField(max_length=100)),
                ('tcoreAsset', models.CharField(max_length=100)),
                ('tcoreActivity', models.CharField(max_length=100)),
                ('tcoreRepairType', models.CharField(max_length=100)),
                ('costCenter', models.CharField(max_length=50)),
                ('entryUser', models.CharField(max_length=50)),
                ('entryDt', models.DateField(default=django.utils.timezone.now)),
                ('approved', models.BooleanField()),
                ('approvedUser', models.CharField(blank=True, max_length=50)),
                ('approvedDt', models.DateField(default=django.utils.timezone.now)),
                ('project', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='mms.Project')),
            ],
        ),
        migrations.CreateModel(
            name='WOOtherContract',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ocDt', models.DateField()),
                ('ocType', models.CharField(max_length=10)),
                ('ocDesc', models.CharField(max_length=100)),
                ('ocCost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('woid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mms.WorkOrder')),
            ],
        ),
        migrations.CreateModel(
            name='WOMaterial',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('mtDt', models.DateField()),
                ('mtDesc', models.CharField(max_length=100)),
                ('mtId', models.IntegerField()),
                ('mtQty', models.DecimalField(decimal_places=1, max_digits=10)),
                ('mtRate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('woid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mms.WorkOrder')),
            ],
        ),
        migrations.CreateModel(
            name='WOLabor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('lbDt', models.DateField()),
                ('employee', models.CharField(max_length=100)),
                ('hours', models.DecimalField(decimal_places=1, max_digits=4)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('woid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mms.WorkOrder')),
            ],
        ),
        migrations.CreateModel(
            name='WOEquip',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('equipDt', models.DateField()),
                ('equipType', models.IntegerField()),
                ('equipDesc', models.CharField(max_length=100)),
                ('equipId', models.IntegerField()),
                ('meterUsage', models.DecimalField(decimal_places=1, max_digits=10)),
                ('meterType', models.CharField(max_length=10)),
                ('equipRate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('woid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mms.WorkOrder')),
            ],
        ),
        migrations.CreateModel(
            name='WOAsset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('assetDt', models.DateField()),
                ('assetType', models.CharField(max_length=20)),
                ('assetIdentifier', models.CharField(max_length=25)),
                ('assetBeginLat', models.DecimalField(blank=True, decimal_places=15, max_digits=17)),
                ('assetBeginLong', models.DecimalField(blank=True, decimal_places=15, max_digits=17)),
                ('assetEndLat', models.DecimalField(blank=True, decimal_places=15, max_digits=17)),
                ('assetEndLong', models.DecimalField(blank=True, decimal_places=15, max_digits=17)),
                ('assetLogStart', models.DecimalField(blank=True, decimal_places=2, max_digits=6)),
                ('assetLogEnd', models.DecimalField(blank=True, decimal_places=2, max_digits=6)),
                ('assetAccomplishment', models.DecimalField(blank=True, decimal_places=1, max_digits=5)),
                ('woid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mms.WorkOrder')),
            ],
        ),
    ]
