# Generated by Django 3.0.6 on 2020-05-27 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorder',
            name='approvedDt',
            field=models.DateField(blank=True),
        ),
    ]
