# Generated by Django 3.0.6 on 2020-05-27 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mms', '0002_auto_20200527_0150'),
    ]

    operations = [
        migrations.AddField(
            model_name='wolabor',
            name='costCenter',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
