# Generated by Django 3.0.6 on 2020-05-27 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mms', '0003_wolabor_costcenter'),
    ]

    operations = [
        migrations.AddField(
            model_name='wolabor',
            name='callback',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
