# Generated by Django 3.0.6 on 2020-05-27 03:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mms', '0006_auto_20200527_0244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorder',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mms.Project'),
        ),
    ]
